### ISSUE TITLE
Control in Continuous Preview Exposure Length and Light Duration Min gone

### ISSUE THREAD

**Issue by Pachacoti** [smart-underworld/seestar_alp#339] opened 2024-10-06 07:48 UTC
I don't see the issue has been reported elsewhere, but correct me if I'm mistaken and if a solution exists. In the web interface, I adjusted Continuous Preview Exposure Length in the settings tab to either 1 or 2 ms and clicked save. Then the box where I used to be able to fill in numbers was gone! Now leaving me only either Enable or Disable options. If I choose on Disable and then save, the web page will show me an XML file of 500 Internal Server Error. The same for Light Duration Min. It used to be -1 and I tweaked it up to some positive value. But then box was gone and I can't restore the old settings. I wonder if there is a solution to these two issues?

**Comment by xscode** [comment] 2024-10-06 10:24
Sounds like a duplicate of error #284?

**Comment by erewhon** [comment] 2024-10-06 18:36
Yes, sorry, that's correct.  It's a duplicate.

The workaround is to specify the values in the config.toml in the `seestar_initialization` section.   I think you have to re-run startup initialization on the Commands page, but I _believe_ that fixes the issue.

**Comment by Pachacoti** [comment] 2024-10-07 05:55
Ah yes, the first issue is indeed a duplicate of error #284, but not the second one. Thanks @erewhon for pointing out the solution! The continuous previous exposure length box is now back, but not the Light Duration Min. I suspect this is due to there being no corresponding command in the config.toml. I don't find a correct way to set that up. Could you tell me what the correct name of the parameter is if I need to add it to the configuration file?

**Closed** 2024-11-18 00:36 UTC
